---
title: "Heart Prediction Model"
author: "Farrah Johnson and Mariam Ikram"
date: "2026-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r}
heart <- read.csv("heart.csv")
glimpse(heart)
```



```{r, include = FALSE}

# takes you to the full database without including it in the knit

view(heart)
```

```{r}
names(heart)
range(heart$Age)
```




```{r}

# Pulls out necessary data and changes the heart disease to a string to make it more decipherable 


set.seed(123)
random_sample <- heart %>%
  sample_n(20)

#I set a seed here so the data we're pulling is more random, as head(20) will only pull the first 20. 

random_sample %>%
  select(Age, Sex, HeartDisease, RestingBP, Cholesterol, MaxHR) %>%
  mutate(HeartDisease = recode(HeartDisease,
                                "1" = "Yes",
                                "0" = "No")) %>%
  arrange(Age) %>%
  head(20)

# gives an average for necessary data for a better comparison


heart %>%
  select(Age, Sex, HeartDisease, RestingBP, Cholesterol, MaxHR) %>%
  mutate(HeartDisease = recode(HeartDisease,
                                "1" = "Yes",
                                "0" = "No")) %>%
  group_by(HeartDisease) %>%
  summarise("Average Blood Pressure" = mean(RestingBP),
            "Average Age" = mean(Age),
            "Cholesterol" = mean(Cholesterol),
            "Max Heart Rate" = mean(MaxHR))






```

```{r}

# cleaned heart data so the graph shows no zero values, histogram w/ facet wrap, changed the labels so it was more decipherable. I used cholesterol for this data because it seemed to have the highest correlation with heart disease, but I'll have to look into it further.

heart_clean <- heart %>%
  filter(Cholesterol != 0)


ggplot(heart_clean, aes(x = Cholesterol, fill = "pink")) + geom_histogram(binwidth = 20) + facet_wrap(~HeartDisease, labeller = labeller(HeartDisease = c("1" = "Has Heart Disease", "0" = "No Heart Disease"))) + labs(title = "Cholesterol distribution",
                                                                                                                                                                                                                        x = "Cholesterol level",
                                                                                                                                                                                                                        y = "People"
)


```






























